apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: izzeddincelik/sample_app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sampleappservice
spec:
  selector:
    app: sampleapp
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30070
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /WeatherForecast
            pathType: Prefix
            backend:
              service:
                name: sampleappservice
                port:
                  number: 80